#!/usr/bin/env python3
"""
satellite_sim.py — Simulates N EPM satellites for multi-satellite gateway testing.

Lets you test recv_verify.py with multiple satellites without buying extra hardware.
Each instance has a unique fake MAC, appears as a distinct satellite in the gateway,
and sends realistic frame data at ~2.2 fps.

Spectra are generated by fault_models.py using physics-grounded bearing fault
signatures: BPFO/BPFI/BSF/FTF tones derived from real bearing geometry (SKF 6205
default), with amplitude-modulated sidebands, broadband resonance excitation, and
time-domain kurtosis/crest matching ISO 10816 run-to-failure data.

Usage:
  python satellite_sim.py [host] [port] [n_satellites]
  python satellite_sim.py 127.0.0.1 5100 3

Fault injection:
  --fault ID    Satellite ID sends progressive bearing fault (severity ramps 0→1)
  --warn  ID    Satellite ID sends stable mid-stage fault (severity held at 0.5)
  --ramp  ID    Like --fault but slow-ramp for adaptive-sensing closed-loop test
  --fault-type  outer|inner|ball|cage (default: cycles across fault IDs)
  --bearing     Bearing model number (default: 6205) or n,D,d[,alpha]
  --shaft-hz    Shaft frequency in Hz (default: 25.0)
  --evolution-hours
                Time (hours) for a progressive fault to reach K_fail.
                Produces exponential kurtosis growth K(t) = K0·exp(λt) so the
                Kalman RUL estimator has a real exponential trajectory to fit.

Satellites automatically reconnect on gateway disconnect.
"""

import argparse
import os
import socket
import struct
import sys
import threading
import time

import numpy as np

# ─── Protocol constants (must match epm_protocol.h) ────────────────────────

HELLO_FMT  = '<I6sBB12s'          # 24 bytes
HEADER_FMT = '<IIIHHffffBfffBBx'  # 48 bytes
V2_FMT     = '<BBHBBBB'           # 8 bytes — epm_alert_v2_t

EPM_HELLO_MAGIC    = 0xEA1D0000
EPM_FRAME_MAGIC    = 0xEA1DF00D
EPM_PROTO_V2_MAGIC = 0xA2

MIC_FS_HZ  = 16000
MIC_BINS   = 512    # FFT_MIC_N / 2 = 1024/2
IMU_BINS   = 1024   # FFT_IMU_N / 2 = 2048/2
IMU_FS_HZ  = 25600

ALERT_MAP = {0: 'OK', 1: 'WARN', 2: 'FAULT'}

# ─── Physics-grounded spectrum generation ────────────────────────────────────

sys.path.insert(0, os.path.dirname(__file__))
from fault_models import (
    generate_mic_frame, make_severity_fn, FAULT_CYCLE,
    DEFAULT_BEARING, DEFAULT_SHAFT_HZ,
)
from bearing_math import BearingFreqs, parse_bearing_arg, COMMON_BEARINGS


def _gen_imu_fft(mode: str, axis: str, rng: np.random.Generator) -> list:
    """
    IMU FFT in dBFS.  Physics-informed but simplified — the contest sensor
    is a microphone, not an accelerometer.  Keeps IMU data realistic enough
    for the gateway's imu_crest threshold checks.
    """
    BIN_HZ = IMU_FS_HZ / (IMU_BINS * 2)
    fft = rng.normal(-97.0, 2.0, IMU_BINS).tolist()
    fft[0] = -120.0

    b50  = round(50  / BIN_HZ)
    b100 = round(100 / BIN_HZ)
    b150 = round(150 / BIN_HZ)

    if axis == 'x' and b50 < IMU_BINS:
        fft[b50]  = -58.0 + rng.normal(0, 1.0)
    elif axis == 'y' and b50 < IMU_BINS:
        fft[b50]  = -59.0 + rng.normal(0, 1.0)
        if b150 < IMU_BINS:
            fft[b150] = -65.0 + rng.normal(0, 1.2)
    elif axis == 'z' and b100 < IMU_BINS:
        fft[b100] = -62.0 + rng.normal(0, 1.0)

    if mode in ('fault', 'warn'):
        scale = 1.0 if mode == 'fault' else 0.5
        for b in range(22, min(33, IMU_BINS)):
            fft[b] = max(fft[b], -60.0 + scale * 10.0 + rng.normal(0, 2.0))

    return fft


def _make_frame(frame_id: int, bearing, shaft_hz: float,
                fault_type: str, severity: float,
                rng: np.random.Generator) -> bytes:
    """Build a complete length-prefixed EPM frame packet."""
    ts_ms = int(time.time() * 1000) & 0xFFFFFFFF

    fft_db, kurtosis, crest, mic_rms = generate_mic_frame(
        n_bins=MIC_BINS, fs_hz=MIC_FS_HZ,
        bearing=bearing, shaft_hz=shaft_hz,
        fault_type=fault_type, severity=severity, rng=rng)

    # IMU stats scale with severity
    imu_rms   = 0.005 + severity * 0.055
    imu_crest = 3.2   + severity * 8.0 + rng.normal(0, 0.3)

    hdr = struct.pack(HEADER_FMT,
                      EPM_FRAME_MAGIC, frame_id, ts_ms,
                      MIC_BINS, IMU_BINS,
                      mic_rms, crest, 0.0, kurtosis, 0,
                      imu_rms, imu_crest, 0.0, 0, 3)

    # Determine alert mode label for IMU generation
    mode = 'ok' if severity < 0.3 else ('warn' if severity < 0.65 else 'fault')

    mic_bytes = struct.pack(f'<{MIC_BINS}f', *fft_db.tolist())
    imu_x     = struct.pack(f'<{IMU_BINS}f', *_gen_imu_fft(mode, 'x', rng))
    imu_y     = struct.pack(f'<{IMU_BINS}f', *_gen_imu_fft(mode, 'y', rng))
    imu_z     = struct.pack(f'<{IMU_BINS}f', *_gen_imu_fft(mode, 'z', rng))

    payload = hdr + mic_bytes + imu_x + imu_y + imu_z
    return struct.pack('<I', len(payload)) + payload


# ─── Gateway reply parsing ───────────────────────────────────────────────────

def _recv_gateway_reply(sock):
    """Read and decode the gateway's v1 or v2 reply.
    Returns (alert_name, extras_str) or (None, None) on closed connection."""
    try:
        first = sock.recv(1)
        if not first:
            return None, None
        b0 = first[0]

        if b0 == EPM_PROTO_V2_MAGIC:
            rest = b''
            while len(rest) < 7:
                chunk = sock.recv(7 - len(rest))
                if not chunk:
                    return None, None
                rest += chunk
            _, alert, posterior, overlap, avg_n, _, _ = struct.unpack(V2_FMT, first + rest)
            alert_name = ALERT_MAP.get(alert, f'0x{alert:02x}')
            p_pct = posterior / 100.0
            extras = f'p_fault={p_pct:.1f}%  OV={overlap}%  AVG={avg_n}'
            return alert_name, extras

        alert_name = ALERT_MAP.get(b0, f'0x{b0:02x}')
        return alert_name, '(v1)'

    except socket.timeout:
        return '(timeout)', ''


# ─── Per-satellite thread ────────────────────────────────────────────────────

def _run_satellite(sat_id: int, host: str, port: int,
                   bearing, shaft_hz: float,
                   fault_mode: str,         # 'ok' | 'warn' | 'fault' | 'ramp'
                   fault_type: str,
                   evolution_sec: float):
    """Connect, stream physics-grounded frames, read v1/v2 reply. Auto-reconnects."""

    mac        = bytes([0xAA, 0xBB, 0xCC, 0xDD, 0x00, sat_id & 0xFF])
    name_str   = f'SIM-{sat_id:02d}'
    name_bytes = name_str.encode('ascii').ljust(12, b'\x00')
    hello      = struct.pack(HELLO_FMT, EPM_HELLO_MAGIC, mac, 1, 0, name_bytes)

    tag     = f'[{name_str}]'
    rng     = np.random.default_rng(sat_id * 7919)   # deterministic per satellite
    frame_id = 0

    # Build severity function for progressive/ramp modes
    sev_fn = make_severity_fn(k_fail=40.0, evolution_seconds=evolution_sec)

    mode_label = f' ({fault_mode.upper()}, {fault_type})'
    print(f'{tag} Starting{mode_label}  bearing={bearing.name}  '
          f'shaft={shaft_hz:.1f} Hz  target={host}:{port}')
    if fault_mode in ('fault', 'ramp'):
        bf = BearingFreqs.from_shaft_hz(shaft_hz, bearing)
        print(f'{tag}   BPFO={bf.bpfo:.2f} Hz  BPFI={bf.bpfi:.2f} Hz  '
              f'BSF={bf.bsf:.2f} Hz  FTF={bf.ftf:.2f} Hz')
        print(f'{tag}   λ={sev_fn.lam:.5f} s⁻¹  '
              f'T_fail={sev_fn.evolution_sec/3600:.2f} h')

    connect_t = None

    while True:
        sock = None
        try:
            sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            sock.settimeout(8.0)
            sock.connect((host, port))
            sock.settimeout(2.5)
            sock.sendall(hello)
            connect_t = time.time()
            print(f'{tag} Connected')

            while True:
                # Compute current severity
                if fault_mode == 'ok':
                    severity = 0.0
                elif fault_mode == 'warn':
                    severity = 0.50
                elif fault_mode in ('fault', 'ramp'):
                    elapsed  = time.time() - connect_t
                    severity = sev_fn(elapsed)
                else:
                    severity = 0.0

                pkt = _make_frame(frame_id, bearing, shaft_hz,
                                  fault_type, severity, rng)
                sock.sendall(pkt)

                alert_name, extras = _recv_gateway_reply(sock)
                if alert_name is None:
                    print(f'{tag} Gateway closed connection')
                    break

                print(f'{tag} frame={frame_id:5d}  sev={severity:.3f}  '
                      f'alert={alert_name}  {extras}')

                frame_id += 1
                time.sleep(0.45)

        except ConnectionRefusedError:
            print(f'{tag} Connection refused — is recv_verify.py running?')
        except Exception as exc:
            print(f'{tag} Error: {exc}')
        finally:
            if sock:
                try:
                    sock.close()
                except OSError:
                    pass

        time.sleep(2.0)


# ─── Entry point ─────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser(
        description='EPM satellite simulator with physics-grounded bearing fault signals',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__)
    ap.add_argument('host', nargs='?', default='127.0.0.1')
    ap.add_argument('port', nargs='?', type=int, default=5100)
    ap.add_argument('n',    nargs='?', type=int, default=3,
                    help='Number of simulated satellites (default: 3)')

    ap.add_argument('--fault', type=int, action='append', default=[], metavar='ID',
                    help='Satellite ID runs progressive bearing fault (severity 0→1)')
    ap.add_argument('--warn',  type=int, action='append', default=[], metavar='ID',
                    help='Satellite ID holds stable mid-stage fault (severity 0.5)')
    ap.add_argument('--ramp',  type=int, action='append', default=[], metavar='ID',
                    help='Like --fault but logged as ramp for adaptive-sensing test')

    ap.add_argument('--fault-type', default='cycle',
                    choices=['outer', 'inner', 'ball', 'cage', 'cycle'],
                    help='Bearing fault type to inject (default: cycle across fault IDs)')
    ap.add_argument('--bearing', default='6205',
                    help='Bearing model (e.g. 6205) or n,D,d[,alpha] (default: 6205)')
    ap.add_argument('--shaft-hz', type=float, default=DEFAULT_SHAFT_HZ,
                    help=f'Shaft frequency Hz (default: {DEFAULT_SHAFT_HZ} = 1500 RPM)')
    ap.add_argument('--evolution-hours', type=float, default=0.5,
                    help='Hours for progressive fault to reach K_fail (default: 0.5)')

    args = ap.parse_args()

    bearing = parse_bearing_arg(args.bearing)
    if bearing is None:
        print(f'Unknown bearing "{args.bearing}".  '
              f'Built-in: {", ".join(sorted(COMMON_BEARINGS))}')
        sys.exit(1)

    evolution_sec = args.evolution_hours * 3600.0

    # Build per-satellite mode and fault-type map
    modes      = {}
    fault_types = {}
    fault_sat_idx = 0   # counter for cycling fault types

    for sid in args.fault:
        modes[sid] = 'fault'
    for sid in args.warn:
        modes[sid] = 'warn'
    for sid in args.ramp:
        modes[sid] = 'ramp'

    for sid in sorted(set(list(args.fault) + list(args.ramp))):
        if args.fault_type == 'cycle':
            fault_types[sid] = FAULT_CYCLE[fault_sat_idx % len(FAULT_CYCLE)]
            fault_sat_idx += 1
        else:
            fault_types[sid] = args.fault_type
    for sid in args.warn:
        fault_types.setdefault(sid, args.fault_type if args.fault_type != 'cycle' else 'outer')

    n_sats = args.n
    print(f'Starting {n_sats} satellite(s) → {args.host}:{args.port}')
    if modes:
        print(f'Fault modes: { {k: (modes[k], fault_types.get(k,"—")) for k in sorted(modes)} }')

    threads = []
    for sid in range(1, n_sats + 1):
        mode = modes.get(sid, 'ok')
        ft   = fault_types.get(sid, 'outer')
        t = threading.Thread(
            target=_run_satellite,
            args=(sid, args.host, args.port, bearing, args.shaft_hz,
                  mode, ft, evolution_sec),
            daemon=True,
            name=f'sat-sim-{sid}')
        t.start()
        threads.append(t)
        time.sleep(0.35)

    try:
        while True:
            time.sleep(60)
    except KeyboardInterrupt:
        print('\nStopped.')
        sys.exit(0)


if __name__ == '__main__':
    main()
